# Generated by Django 6.1 on 2026-08-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivyaserver', '0003_product_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_name', models.CharField(max_length=200)),
                ('faq_question', models.TextField()),
                ('faq_answer', models.TextField()),
            ],
        ),
    ]
