# Generated by Django 6.1 on 2026-09-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivyaserver', '0008_paymentprovider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
