# Generated by Django 6.1 on 2026-09-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivyaserver', '0009_rename_phone_number_user_phonenumber_user_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
