# Generated by Django 6.1 on 2026-09-04 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivyaserver', '0011_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_qty',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
