# Generated by Django 6.1 on 2026-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivyaserver', '0013_order_orderdet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
