# Generated by Django 6.1 on 2026-09-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivyaserver', '0014_order_order_code_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
