# Generated by Django 6.1 on 2026-09-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivyaserver', '0017_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
