# Generated by Django 6.1 on 2026-09-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivyaserver', '0019_alter_user_managers_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_qty',
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_variation', models.CharField(max_length=200)),
                ('variation_image', models.ImageField(upload_to='productvariations/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_details', to='trivyaserver.product')),
            ],
        ),
    ]
