# Generated by Django 6.1 on 2026-09-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivyaserver', '0020_remove_product_product_qty_productdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='variation_image',
        ),
        migrations.AddField(
            model_name='product',
            name='variation_image_four',
            field=models.ImageField(blank=True, null=True, upload_to='productvariations/'),
        ),
        migrations.AddField(
            model_name='product',
            name='variation_image_one',
            field=models.ImageField(blank=True, null=True, upload_to='productvariations/'),
        ),
        migrations.AddField(
            model_name='product',
            name='variation_image_three',
            field=models.ImageField(blank=True, null=True, upload_to='productvariations/'),
        ),
        migrations.AddField(
            model_name='product',
            name='variation_image_two',
            field=models.ImageField(blank=True, null=True, upload_to='productvariations/'),
        ),
    ]
