# Generated by Django 6.1 on 2026-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivyaserver', '0022_remove_product_price_productdetails_price_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variation_image_four',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variation_image_one',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variation_image_three',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variation_image_two',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='variation_image_four',
            field=models.ImageField(blank=True, null=True, upload_to='productvariations/'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='variation_image_one',
            field=models.ImageField(blank=True, null=True, upload_to='productvariations/'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='variation_image_three',
            field=models.ImageField(blank=True, null=True, upload_to='productvariations/'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='variation_image_two',
            field=models.ImageField(blank=True, null=True, upload_to='productvariations/'),
        ),
    ]
