# Generated by Django 6.1 on 2026-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivyaserver', '0023_remove_product_variation_image_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdet',
            name='product_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
